name: branch-checker

on:
  push:
    branches:
      - '*'
jobs:
  branch-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Get All dependency
        run: go get -v ./...
      - name: Unit Test
        run : make test